language: java
jdk: oraclejdk8

services:
  - mysql
sudo: true

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS BLOG;'  
  - mysql -u root --default-character-set=utf8 BLOG < scripts/blog.sql